### PR TITLE
Add basic chunk system for infinite world environment

### PR DESCRIPTION
**Pull request by jackguo336**
This PR includes the following additions to the game:
- Chunk management, such as generating and removing chunks as the player moves through the world
- Magnet objects being spawned randomly by each chunk
- A world bound that keeps the player close to the origin (by teleporting them back if they move too far)
- Fixes sprites of game objects sometimes covering each other by offsetting their z-axis positions
- Fixes stuttering movement of player

Things to consider adding in the future:
- Reducing the frequency of chunk updates
- Using seeds to ensure the same objects are spawned by the same chunk
- Adding biomes

### CODE REVIEW

**Comment by RichardZJM** [comment]
Looks pretty good although I'm not sure why the OnSlimeMoved function is handled in the MagnetController rather than the WorldBound itself.

**Comment by RichardZJM** [comment]
Other than that weird point, I'm good to merge when Leon is.

**Comment by leonchen0613** [comment]
Yeah looks amazing, set for merge.

**Comment by jackguo336** [comment]
> Looks pretty good although I'm not sure why the OnSlimeMoved function is handled in the MagnetController rather than the WorldBound itself.

Currently `OnSlimeMoved` is handled in the MagnetController because it is getting the Cinemachine camera attached to the slime. If you know a better way to do this, feel free to modify the code.

**Pull request merged**
